services:
  - type: web
    name: pdf-to-musicxml
    env: python
    buildCommand: ./render-build.sh
    startCommand: python pdf_to_musicxml.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000 