services:
  - type: web
    name: audiveris-flask-api
    env: python
    buildCommand: ./render-build.sh
    startCommand: python pdf_to_musicxml.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 