services:
  - type: web
    name: audiforge-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1
    disk:
      name: downloads
      mountPath: /tmp/downloads
      sizeGB: 1 